### PR TITLE
Made needed changes to use for US_CMS_FNAL_T1 xrootd site and regional redirectors

### PR DESCRIPTION
**Pull request by gerardba**
Added some more config variables, instances_options now have -k fifo like default xrootd RPM, template xrootd.cfg.erb xrootd_instances_options array fixed and idented template content, all.manager converted in an array. Removed duplicated oss.localroot entry in xrootd.xfg.erb

### CODE REVIEW

**Comment by andrea-manzi** [comment]
thanks! will do some tests and publish a new version to puppetforge

**Comment by andrea-manzi** [comment]
Hi Gerard,
when testing your changes i'm getting this error

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse template xrootd/sysconfig.erb:
  Filepath: /mnt/puppetnfsdir/environments/qa/modules/xrootd/templates/sysconfig.erb
  Line: 25
  Detail: comparison of Hash with Hash failed
 at /mnt/puppetnfsdir/environments/qa/modules/xrootd/manifests/create_sysconfig.pp:23 on node p01001533u01293.cern.ch

are you using a particular version of puppet ?

**Comment by gerardba** [comment]
Hi Andrea,

I am using puppet-3.6.2-1.el6.noarch on both client and server.

This is how my redirector profile (what calls this xrootd module) looks
like:


 xrootd::create_config{'/etc/xrootd/xrootd.cfg':
    require => Class['xrootd'],
    xrd_allrole => 'manager',
    cmsd_allrole => 'manager',
    all_manager  => ["${::fqdn}:1213", "cmsxrootd.fnal.gov+:1213", "meta
any cms-xrd-global.cern.ch+:1098"],
    xrootd_monitor => 'all auth flush 30s mbuff 1472 window 5s dest files
io info redir user xrootd.t2.ucsd.edu:9930',
    xrd_report => 'xrootd.t2.ucsd.edu:9931 every 30s all sync',
    cms_allow => [
                  'host *.brown.edu',
                  'host *.crc.nd.edu',
                  'host *.fnal.gov',
                  'host *.mit.edu',
                  'host *.neu.edu',
                  'host *.purdue.edu',
                  'host *.sprace.org.br',
                  'host *.tusker.hcc',
                  'host *.ucsd.edu',
                  'host *.uerj.br',
                  'host *.ultralight.org',
                  'host *.ufl.edu',
                  'host *.unl.edu',
                  'host *.uprm.edu',
                  'host *.vanderbilt.edu',
                  'host *.wisc.edu',
                ],
    cms_fxhold => '1200s',
    all_sitename => 'T1_US_FNAL',
    cms_ping => '30',
    xrd_network => 'keepalive kaparms 5m,5s,5',
    xrd_timeout => 'idle 30m',
    cms_sched => 'cpu 0 runq 0 io 0 mem 0 fuzz 100 refreset 3600',
    #    xrd_sched => 'mint 8 maxt 20480 avlt 512 idle 78', #According to
Marian we do not need this anymore.
    cms_delay => 'startup 10 lookup 1 qdl 30 qdn 2 servers 1',
    ofs_authorize => false,
    xrootd_fslib => '/usr/lib64/libXrdOfs.so',
    xrootd_redirect => 'cms-xrd-global.cern.ch:1094 ? /store/',
    xrootd_export => ['/store/'],
    xrd_port  => 1094,
    xrd_debug => true, #TODO: remove once production ready, just for
commissioning testing/debugging!
  }
  xrootd::create_sysconfig{'/etc/sysconfig/xrootd':
    xrootd_instances_options => {
      'default' => "-l /var/log/xrootd/xrootd.log -c /etc/xrootd/xrootd.cfg
-k fifo",
    },
    cmsd_instances_options   => {
      'default' => "-l /var/log/xrootd/cmsd.log -c /etc/xrootd/xrootd.cfg
-k fifo",
    },
    xfrd_instances_options   => {
      'default'  => "-l /var/log/xrootd/frmd.log -c /etc/xrootd/xrootd.cfg
-k fifo",
    },
  }


Gerard

2015-09-15 10:08 GMT-05:00 Andrea <notifications@github.com>:

**Comment by andrea-manzi** [comment]
Hi Gerard,
so i investigate the problem and i found out that the we are using in another module the xrootd_instances_options as an array of hash, and not an hash as the other options. See: 

https://github.com/cern-it-sdc-id/puppet-dmlite/blob/master/manifests/xrootd.pp#L201-L236

this is way your change breaks our installation ( DPM)

i have reverted some changes you have done in my latest commit, you have just to modify the way you invoke the xrootd::create_sysconfig, by passing the  xrootd_instances_options value as as an array of hashes

let me know if this is ok for you
Andrea

**Comment by gerardba** [comment]
thanks for the explanations! I've made another pull request to add this
info in params.pp:

https://github.com/cern-it-sdc-id/puppet-xrootd/pull/3

Thanks,
 Gerard

2015-09-17 5:03 GMT-05:00 Andrea <notifications@github.com>:

**Pull request merged**
